CREATE TABLE IF NOT EXISTS teacher (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(60) NOT NULL,
  email VARCHAR(254) NOT NULL
);

CREATE TABLE  IF NOT EXISTS tasks (
    id  BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	status BOOLEAN NOT NULL,
	title  VARCHAR(100) NOT NULL,
	lmt DATE NOT NULL
);